### ISSUE TITLE
inconsistent balance displays

### ISSUE THREAD

**Issue by evanliuchina** [mengguang/uniswap-interface#1]
**Bug Description**
After swapping NEW/MSK2, balance numbers shown in NewMask, newswap web interface (right-up corner) and newswap web interface (swapping area) are different.

**Steps to Reproduce**
1. Go to https://newswap.testnet.cloud.diynova.com/
2. Swap NEW for MSK2
3. Check the balance numbers shown in three places as described above.

![image](https://user-images.githubusercontent.com/63840843/93051288-d0648f80-f696-11ea-8590-93c0967ccfac.png)

![image](https://user-images.githubusercontent.com/63840843/93051258-c478cd80-f696-11ea-869c-e320c063992f.png)

![image](https://user-images.githubusercontent.com/63840843/93051268-c9d61800-f696-11ea-810c-7b26558b65f7.png)

The three numbers are inconsistent.

**Expected Behavior**

The balance numbers should be the same and consistent.

**Additional Context**

It seems you need to have > 10M NEW for reproduce the bug.
Chenzhong has already reproduced it.

**Comment by mengguang** [comment]
fix 595c1af029b8abba8895deb026da1ec2cfc8b802

**Comment by evanliuchina** [comment]
Verified. both are fixed.

![image](https://user-images.githubusercontent.com/63840843/93058769-6356f700-f6a2-11ea-9997-d891a792add2.png)

![image](https://user-images.githubusercontent.com/63840843/93058795-6ce05f00-f6a2-11ea-8283-1db420e8d882.png)
